battery_bms_0: channel_1
battery_bms_1: channel_1
battery_bms_2: channel_2
battery_bms_3: channel_2
battery_bms_4: channel_3
battery_bms_5: channel_3
battery_bms_6: channel_4
battery_bms_7: channel_4
battery_bms_8: channel_5
battery_bms_9: channel_5
battery_bms_10: channel_6
battery_bms_11: channel_6
battery_bms_12: channel_7
battery_bms_13: channel_7
battery_bms_14: channel_8
battery_bms_15: channel_8
battery_bms_16: channel_9
battery_bms_17: channel_9
battery_bms_18: channel_10
battery_bms_19: channel_10
battery_bms_20: channel_11
battery_bms_21: channel_11
battery_bms_22: channel_12
battery_bms_23: channel_12
